name: intake-examples
channels:
  - conda-forge
dependencies:
  - intake
  - jupyter
  - nodejs
  - s3fs
  - tqdm
  - intake-xarray
  - bokeh==1.1.0
  - pyviz::hvplot==0.4.0
  - pyviz::holoviews==1.12.1
  - pyviz::panel==0.5.1
