package:
  version: '0.1.0'
  name: 'airline_flights'

build:
  number: 2
  noarch: generic

requirements:
  run:
    - intake
    - intake-parquet
    - s3fs
  build: []

about:
  description: Airline Flight data
  license: MIT
  license_family: MIT
  summary: Airline flight data
